In [10]:
import numpy as np

In [11]:
list=[1,2,3,4]
arr=np.array(list)
arr


array([1, 2, 3, 4])

In [12]:
ar=np.array([1,6,7,'a',9.0]) #1d

In [13]:
ar

array(['1', '6', '7', 'a', '9.0'], dtype='<U32')

In [14]:
print("size:",ar.size) #attributes
print("dimension:",ar.ndim)
print("datatype:",ar.dtype)
print("shape:",ar.shape)
print("itemsize:",ar.itemsize)

size: 5
dimension: 1
datatype: <U32
shape: (5,)
itemsize: 128


In [15]:
td=np.array([[1,2,3],[4,5,7],[4,5,6]]) #2d
td

array([[1, 2, 3],
       [4, 5, 7],
       [4, 5, 6]])

In [16]:
print("size:",td.size)
print("dimention:",td.ndim)
print("shape:",td.shape)
print("size:",td.dtype)
print("itemsize:",td.itemsize)

size: 9
dimention: 2
shape: (3, 3)
size: int32
itemsize: 4


In [17]:
ar=np.array([1,6,7],dtype=float) #ways to create numpy
ar

array([1., 6., 7.])

In [18]:
ml=np.arange(7)
ml

array([0, 1, 2, 3, 4, 5, 6])

In [19]:
ay=np.ones((2,3))
ay

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
ay=np.zeros((3,4))
ay

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
array=([-2,3,55,64]) #slicing
array[0:2]
array[1:]

[3, 55, 64]

In [22]:
a=np.array([[1,2,3],[4,5,1]]) #addition
y=np.array([[2,3,1],[2,1,3]])
a+y

array([[3, 5, 4],
       [6, 6, 4]])

In [23]:
a=np.array([4,7,8,9,0,1]) #sorting in 1d
a.sort()
a

array([0, 1, 4, 7, 8, 9])

In [43]:
a=np.array([[1,8,3],[9,5,11]]) #2d sort
a

array([[ 1,  8,  3],
       [ 9,  5, 11]])

In [44]:
a.sort(axis=0)
a

array([[ 1,  5,  3],
       [ 9,  8, 11]])

In [46]:
a=np.array([[2,3,4],[4,5,6]]) #concatenate
a

array([[2, 3, 4],
       [4, 5, 6]])

In [47]:
y=np.array([[3,4,5],[6,7,8]])
y

array([[3, 4, 5],
       [6, 7, 8]])

In [51]:
np.concatenate((a,y),axis=1)

array([[2, 3, 4, 3, 4, 5],
       [4, 5, 6, 6, 7, 8]])

In [1]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]]) #shape

print(arr.shape)

(2, 4)


In [2]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]) #reshape

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [3]:
arr = np.array([1, 2, 3]) #iterating

for x in arr:
  print(x)

1
2
3


In [5]:
arr = np.array([3, 2, 0, 1]) #sort

print(np.sort(arr))

[0 1 2 3]


In [6]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8]) #search

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [8]:
arr = np.array([1, 2, 3, 4, 5, 6]) #split

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]
